### ISSUE TITLE
tesser.utils/update replacing clojure.core/update

### ISSUE THREAD

**Issue by andrewsuzuki** [aphyr/tesser#12]
Getting these errors when requiring tesser.simple:

`WARNING: update already refers to: #'clojure.core/update in namespace: tesser.utils, being replaced by: #'tesser.utils/update`
`WARNING: update already refers to: #'clojure.core/update in namespace: tesser.core, being replaced by: #'tesser.utils/update`
`WARNING: update already refers to: #'clojure.core/update in namespace: tesser.simple, being replaced by: #'tesser.utils/update`

**Comment by neverfox** [comment]
Also `bytes?` now too. The way this was implemented, it was [hardcoded to fix 1.7.0](https://github.com/aphyr/tesser/blob/master/core/src/tesser/utils.clj#L84) only.

**Comment by thedavidmeister** [comment]
I'm getting this with math

```
WARNING: update already refers to: #'clojure.core/update in namespace: tesser.utils, being replaced by: #'tesser.utils/update
WARNING: update already refers to: #'clojure.core/update in namespace: tesser.core, being replaced by: #'tesser.utils/update
WARNING: update already refers to: #'clojure.core/update in namespace: tesser.math, being replaced by: #'tesser.utils/update
WARNING: update already refers to: #'clojure.core/update in namespace: tesser.quantiles, being replaced by: #'tesser.utils/update
WARNING: update already refers to: #'clojure.core/update in namespace: clojure.math.combinatorics, being replaced by: #'clojure.math.combinatorics/update
```

**Comment by thedavidmeister** [comment]
I'm getting this in clojure 1.7.0 too.

`WARNING: update already refers to: #'clojure.core/update in namespace: clojure.math.combinatorics, being replaced by: #'clojure.math.combinatorics/update`

**Comment by thedavidmeister** [comment]
@aphyr could we just add this? http://spootnik.org/entries/2014/11/03_heads-up-for-clojure-library-writers.html

**Comment by aphyr** [comment]
1.7's been out long enough. We can probably just drop `update`.

**Comment by ktsujister** [comment]
Hi, I was just wondering if you can make release with this change. (with #20)
